### ISSUE TITLE
problem with send posts

### ISSUE THREAD

**Issue by c0derman** [Baha2Odeh/HlounPost2#1]
hey

when i try to send post i saw this error

Field 'is_shared' doesn't have a default value

https://docs.google.com/file/d/0BwtuL8cAPh4AWnJtX1VpbWlEMm8/edit?usp=drivesdk

and if i add post from phpymyadmin i got this error

Field 'totalcount' doesn't have a default value

**Comment by c0derman** [comment]
https://docs.google.com/file/d/0BwtuL8cAPh4AWnJtX1VpbWlEMm8/edit?usp=drivesdk

**Comment by c0derman** [comment]
any help

**Comment by hloun** [comment]
can you run this query in your phpmyadmin

CREATE TABLE IF NOT EXISTS `posts` (
									  `id` int(11) NOT NULL AUTO_INCREMENT,
									  `date` text NOT NULL,
									  `type` int(11) NOT NULL,
									  `is_shared` int(11) NOT NULL,
									  `text` text NOT NULL,
									  `link` text NOT NULL,
									  PRIMARY KEY (`id`)
									) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

**Comment by c0derman** [comment]
thanks i will try it now , about new version of hlounpost can u upload it , i feel happy about send to twitter and short links ^^
waiting your new update as possible

**Comment by c0derman** [comment]
no any change

total errors 2

Field 'totalcount' doesn't have a default value
and
Field 'is_shared' doesn't have a default value

last error was view in post page but now redirect to white page

how we solve this problem or better upload new version

**Comment by c0derman** [comment]
i solve problem with errors and its 4 mysql errors

ALTER TABLE posts MODIFY is_shared int NOT NULL DEFAULT '0'
ALTER TABLE task MODIFY totalcount int NOT NULL DEFAULT '0'
ALTER TABLE task MODIFY successed int NOT NULL DEFAULT '0'
ALTER TABLE task MODIFY failed int NOT NULL DEFAULT '0'

but now 

لم ينجح النشر عند Mai Ataya
OAuthException: (#200) Requires extended permission: publish_actions

i try now with this permission in developer area but i hope u share new version

waiting u

**Comment by c0derman** [comment]
another error showing permission needed

Invalid Scopes: publish_stream, photo_upload, offline_access. This message is only shown to developers. Users of your app will ignore these permissions if present. Please read the documentation for valid permissions at: https://developers.facebook.com/docs/facebook-login/permissions

but test account send successfully photo

it script need this permission to work good or not needed?

**Comment by c0derman** [comment]
facebook deny publish_actions

"Your app needs to reflect the environment that real users experience. Please build out functionality before resubmitting for review.
If your app is fully developed, please update your instructions and screenshots so that we can finish testing your app."

now what we can do in script to make facebook accept publish_actions permission?

**Comment by c0derman** [comment]
any new update?

**Comment by hloun** [comment]
You need to submit your app to facebook to approve the permission you request

**Comment by c0derman** [comment]
i did baha but facebook need more info about my app

if u want screen from my developer area no problem i will but how i active this permission

and about new version u will share it cuz i need to start edit stable version or at less good ver with same good edit

waiting u answer to help me for active permission and new version

**Comment by c0derman** [comment]
any new update for this files?

**Comment by hloun** [comment]
to now i didn't get approved for my application , the new version not developed yet

**Comment by c0derman** [comment]
so ur problem now with publish_actions tow? and can u send the new version to edit same functions like many users register and same ideas i have

**Comment by c0derman** [comment]
the new problem now with publish_actions i think facebook need same site with vote function

baha please be with me to solve the problem with facebook or send last version ur edit to start edit with it and add same ideas to be with last facebook terms of service like ur have the same problem , add me on skype to contact

c0der.man

waiting u

**Comment by c0derman** [comment]
baha this site for my friend he edit ur frist version and add good ideas and heis work good for now we need same edit to add but i waiting u last edit to start edit for it

this is site https://elebda3.com/share/

i think ssl is needed for facebook accept app

waiting u for answer

**Comment by c0derman** [comment]
baha u there?

**Comment by c0derman** [comment]
any new update , i got ssl from one friend

**Comment by c0derman** [comment]
any new update?

**Comment by c0derman** [comment]
any one there??

baha please upload new version to start edit with it

**Comment by c0derman** [comment]
problem with register white page

https://3eba.com/face/register.php?step=login#access_token=CLTEYBAImfwems7j211nHVpNzllAWoMdywMM6CsJPdlvprwc3IJLl6vmmoSXESieSxZBggIllGpXC6ScRF5h2Qm2HVE22fHitU3MoKHI1TEXPGRn7XEY3cZCy2qZCIeEyc7ZCZBl6lMkVBYr9bZBAjevBhUkyfmrQwoSdMb7yLMLsv4AW4vFZCmGZB47&expires_in=6713\

what is this problem
print from facebook team
http://im82.gulfup.com/3yN94U.png
other print
http://im82.gulfup.com/v52d6j.png
